# Generated by Django 5.2.3 on 2025-07-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_teacherextra_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherextra',
            name='department',
            field=models.CharField(choices=[('Maths', 'Mathematics'), ('Science', 'Science'), ('English', 'English'), ('Hindi', 'Hindi'), ('Social', 'Social Science'), ('Computer', 'computer'), ('physics', 'physics'), ('chemistry', 'chemistry'), ('biology', 'biology')], max_length=200),
        ),
    ]
