# Generated by Django 5.2.3 on 2025-07-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_teacherextra_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('experience', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='profiles/')),
                ('bio', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('teacher', 'Teacher'), ('10th_topper', '10th Topper'), ('12th_topper', '12th Topper'), ('best_in_class', 'Best in Class')], max_length=50)),
            ],
        ),
    ]
