# Generated by Django 5.2.3 on 2025-07-15 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='cl',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='present_status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='roll',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='school.studentextra'),
            preserve_default=False,
        ),
    ]
