# Generated by Django 5.2.3 on 2025-07-15 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_alter_attendance_id_alter_notice_id_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='admission_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
